language: julia
os:
  - linux
  - osx
notifications:
  email: false
julia:
  - release
  - nightly
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.init(); Pkg.add("PyCall"); Pkg.add("RDatasets"); Pkg.clone(pwd()); Pkg.test("Vega")'